import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useQuery } from '@tanstack/react-query';
import { get } from '../../lib/api';
import { money, dateIn } from '../../lib/format';
import { Badge, Empty, Loading, Panel, Stat, Table, Td, PageTitle } from '../../components/ui';
export default function MyFees() {
    const { data, isLoading } = useQuery({ queryKey: ['my-fees'], queryFn: () => get('/fees/mine') });
    if (isLoading)
        return _jsx(Loading, {});
    if (!data?.rows.length)
        return _jsx(Empty, { title: "No fee assigned yet" });
    return (_jsxs(_Fragment, { children: [_jsx(PageTitle, { title: "My fees", subtitle: "What is payable, what is paid, and the receipts." }), _jsxs("div", { className: "grid grid-cols-3 gap-3 mb-4", children: [_jsx(Stat, { label: "Total payable", value: money(data.total) }), _jsx(Stat, { label: "Paid", value: money(data.paid), tone: "grass" }), _jsx(Stat, { label: "Balance", value: money(data.balance), tone: data.balance > 0 ? 'amber' : 'grass' })] }), data.rows.map((r) => (_jsxs("div", { className: "mb-4 space-y-4", children: [_jsx(Panel, { title: r.structure, subtitle: r.concession ? `Concession ${money(r.concession)}` : undefined, children: _jsxs(Table, { head: ['Head', 'Amount'], children: [r.heads.map((h) => (_jsxs("tr", { children: [_jsx(Td, { children: h.name }), _jsx(Td, { className: "tabular", children: money(h.amount) })] }, h.name))), _jsxs("tr", { className: "font-semibold", children: [_jsx(Td, { children: "Net payable" }), _jsx(Td, { className: "tabular", children: money(r.netPayable) })] })] }) }), _jsx(Panel, { title: "Installments", children: _jsx(Table, { head: ['Installment', 'Due date', 'Amount', 'Paid', 'Status'], children: r.installments.map((i) => (_jsxs("tr", { children: [_jsx(Td, { className: "tabular", children: i.seq }), _jsx(Td, { className: "tabular", children: dateIn(i.dueDate) }), _jsx(Td, { className: "tabular", children: money(i.amount) }), _jsx(Td, { className: "tabular", children: money(i.paidAmount) }), _jsx(Td, { children: i.paidAmount >= i.amount ? (_jsx(Badge, { tone: "present", children: "paid" })) : i.isOverdue ? (_jsx(Badge, { tone: "absent", children: "overdue" })) : (_jsx(Badge, { tone: "pending", children: "due" })) })] }, i.seq))) }) }), r.receipts.length > 0 && (_jsx(Panel, { title: "Receipts", children: _jsx(Table, { head: ['Receipt', 'Amount', 'Mode', 'Date'], children: r.receipts.map((p) => (_jsxs("tr", { className: p.isCancelled ? 'text-gray-400 line-through' : '', children: [_jsx(Td, { className: "tabular", children: p.receiptNo }), _jsx(Td, { className: "tabular", children: money(p.amount) }), _jsx(Td, { children: p.mode.toLowerCase() }), _jsx(Td, { className: "tabular", children: dateIn(p.paidAt) })] }, p.id))) }) }))] }, r.id)))] }));
}
